# Generated by Django 6.0.2 on 2026-03-03 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasks_local_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbtaskresult',
            options={'ordering': [models.OrderBy(models.F('priority'), descending=True), models.OrderBy(models.F('run_after'))], 'verbose_name': 'task result', 'verbose_name_plural': 'task results'},
        ),
        migrations.RenameIndex(
            model_name='dbtaskresult',
            new_name='django_task_backend_0535b8_idx',
            old_name='django_task_backend_b87c8f_idx',
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='args_kwargs',
            field=models.JSONField(verbose_name='args kwargs'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='backend_name',
            field=models.CharField(max_length=32, verbose_name='backend name'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='enqueued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='enqueued at'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='exception_class_path',
            field=models.TextField(default='', verbose_name='exception class path'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='finished at'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='queue_name',
            field=models.CharField(default='default', max_length=32, verbose_name='queue name'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='return_value',
            field=models.JSONField(default=None, null=True, verbose_name='return value'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='run_after',
            field=models.DateTimeField(null=True, verbose_name='run after'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='started at'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful')], default='READY', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='task_path',
            field=models.TextField(verbose_name='task path'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='traceback',
            field=models.TextField(default='', verbose_name='traceback'),
        ),
        migrations.AlterField(
            model_name='dbtaskresult',
            name='worker_ids',
            field=models.JSONField(default=list, verbose_name='worker ids'),
        ),
        migrations.AddIndex(
            model_name='dbtaskresult',
            index=models.Index(fields=['queue_name'], name='django_task_queue_n_7c9efa_idx'),
        ),
    ]
