# Generated by Django 6.0.2 on 2026-03-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasks_local_db', '0002_alter_dbtaskresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbtaskresult',
            options={'ordering': [models.OrderBy(models.F('priority'), descending=True), 'enqueued_at'], 'verbose_name': 'task result', 'verbose_name_plural': 'task results'},
        ),
        migrations.RemoveIndex(
            model_name='dbtaskresult',
            name='local_db_ready_idx',
        ),
        migrations.AddIndex(
            model_name='dbtaskresult',
            index=models.Index(models.F('status'), models.OrderBy(models.F('priority'), descending=True), models.F('enqueued_at'), condition=models.Q(('status', 'READY')), name='local_db_ready_idx'),
        ),
        migrations.RemoveField(
            model_name='dbtaskresult',
            name='run_after',
        ),
    ]
