# Generated by Django 6.0.2 on 2026-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasks_local_db', '0003_alter_dbtaskresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtaskresult',
            name='last_heartbeat_at',
            field=models.DateTimeField(null=True, verbose_name='last heartbeat at'),
        ),
        migrations.AddField(
            model_name='dbtaskresult',
            name='run_after',
            field=models.DateTimeField(null=True, verbose_name='run after'),
        ),
    ]
